name: UnlimitedEnchantmentLevel
version: '${version}'
main: kr.roinwar.unlimitedenchantmentlevel.UnlimitedEnchantmentLevel
api-version: 1.19
authors: [ Yellowstrawberry ]
description: Unlimited Enchantment Level
website: roinwar.kr
